version: '3.1'

services:
  sigtca_db:
    image: postgres:15.0
    restart: always
    container_name: sigtca_db_main
    ports:
      - 5433:5432
    networks:
      - pg
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: admin
    volumes:
      - pg_data:/var/lib/postgresql/data

  odoo:
    image: odoo:16.0
    restart: always
    container_name: sigtca_main
    ports:
      - 8083:8083
    networks:
      - pg
    links:
      - sigtca_db:db
    environment:
      USER: odoo
      PASSWORD: admin
      CORS_ALLOW_ORIGIN: "*"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf

    tty: true

networks:
  pg:

volumes:
  pg_data: