version: '3.1'

services:
  web:
    image: odoo:16
    ports:
      - "8083:8083"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=admin
      - PGPORT=5436
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=admin
    ports:
      - "5436:5432"

volumes:
  odoo-web-data:
